### ISSUE TITLE
Thumbnail creation breaks if CONVERT_BINARY doesn't accept -alpha

### ISSUE THREAD

**Issue by edgewood** [the-paperless-project/paperless#114]
I'm evaluating paperless, currently installed bare-metal in a virtualenv on Ubuntu 12.04LTS (yeah, I know, very old).  It seems to be working well, except that thumbnails aren't being created, apparently because 'convert' in 12.04 doesn't accept the -alpha argument.  Document conversion dies after each PDF, but gets far enough along that the rest of the process works.

Here's an excerpt from the log, including the last bit of the stack trace:

```
Starting document consumer at /home/me/tmp/paperless
Consuming /home/me/tmp/paperless/test.pdf
Generating greyscale image from /home/me/tmp/paperless/test.pdf
Processing sheet: /tmp/paperless/paperlessp3qe1kuw/convert-0000.pnm -> /tmp/paperless/paperlessp3qe1kuw/convert-0000.unpaper.pnm
out of deviation range - NO ROTATING
Generating the thumbnail
convert: UnrecognizedAlphaChannelType 'remove' @ error/convert.c/ConvertImageCommand/655.
OCRing the document
Parsing for eng
Traceback (most recent call last):
  File "./manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
[...]
  File "/home/me/projects/paperless/src/documents/consumer.py", line 129, in consume
    document = self._store(self._get_ocr(imgs), doc, thumbnail)
  File "/home/me/projects/paperless/src/documents/consumer.py", line 321, in _store
    with open(thumbnail, "rb") as unencrypted:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/paperless/paperlessp3qe1kuw/convert-0000.png'
```

Thoughts:
1. document minimum binary versions (eg, Imagemagick >= 6.7.5, as that's when -alpha remove was added) for bare-metal installs, or maybe crowdsource minimum versions of the major target platforms ("Users have reported success on Debian Wheezy and newer, Fedora XX and up, ...")
2. providing a way to override the CONVERT_BINARY doesn't help much when you then feed that program fixed arguments specific to `convert`.  In my case I could pass a shell script that drops out the -alpha arguments, but if someone wanted to use something completely different it would be harder.  Or is `convert` required, and CONVERT_BINARY just for pointing to a different location if the correct version isn't in the PATH?
3. should return code of CONVERT_BINARY (and others?) be checked?
4. since things appear to work without the thumbnails, maybe the code should catch the exception and warn that the thumbnail wasn't created, but that conversion is proceeding without it

Some, or maybe all, of these should be separate issues, but as a newcomer I figured that opening a handful of issues wouldn't be a great way to start.  I'll be happy to open issues for any that should be fixed.

**Comment by danielquinn** [comment]
I'll hit each of these in point-form.

1. This is a good idea and I'll definitely include a reference to a more specific minimum for ImageMagick at the very least.
2. This is a good point and not one I'd considered.  The idea was just to allow people to reference an explicit path for their `convert`

**Comment by stgarf** [comment]
@edgewood Whoa an oldie! Anything change over the last three years or so? I'm just going through old issues in the repo to see what can potentially be worked on still or cleaned up. This one seems like it's potentially related to #447, can you confirm/deny?

**Comment by edgewood** [comment]
I don't think this is related to #447.  Basically I was trying to run on bare metal and had an old version of ImageMagick that didn't take the arguments that Paperless gave it.

Paperless now documents that ImageMagick 6.7.5 or higher is required, and I gave up on trying to run it in bare metal and now run it inside Docker, making it much easier to keep requirements up to date.

Point number 3 might be worth opening a ticket to fix if it hasn't been fixed already in another ticket, but I don't have the time to check so I'll just close this one.
