### ISSUE TITLE
RFE: Auto re-tag when adding tags

### ISSUE THREAD

**Issue by iFloris** [the-paperless-project/paperless#135]
Would it not be sensible to schedule a retag operation when a user has added tags? For instance, user adds tag(s) -> schedule retag for 23:59 that night -> next day all documents are retagged with the newly added tag(s)

**Comment by Ulli2k** [comment]
good idea or a few minutes after adding or changing a new tag and correspondence

**Comment by maur** [comment]
Even manual link "retag this tag" would be nice

**Comment by danielquinn** [comment]
That's a cool idea, but currently, there's no concept of "schedule" in Paperless, so this is a non-trivial thing to add.  To do it right, you'd need to add Celery and a queue server so the webserver could issue async tasks for events like creating a new tag.

The thing is, that's a lot of moving parts for a system that's designed to work in a self-hosted, not-necessarily-containerised environment.  If we were to add this, it'd have to be coded in such a way that it was optional so Paperless would still work without requiring all of that.

Alternatively, just putting `./manage.py document_retagger` in your crontab would accomplish the same thing.  Just run it once a night and you're good.  This however would retag all documents *for all available tags* which may not be what you want.

A better system might be `./manage.py document_retagger <tag-name>`, and that can be done by modifying the management command to take an argument.  If any of you wanna try your hand at that one, I'd be happy to handle the pull request :-)

**Comment by stgarf** [comment]
@iFloris A [document retagger](https://paperless.readthedocs.io/en/latest/utilities.html#the-re-tagger) has been added... Does this satisfy your request? I'm just going through old issues in the repo to see what can potentially be worked on still or cleaned up.

**Comment by iFloris** [comment]
Sorry, I switched away from paperless not long after opening this issue. @stgarf. I really appreciate that you are cleaning up old issues though! Paperless is an awesome project 🤘
