### ISSUE TITLE
Docker webserver doesn't start without PAPERLESS_PASSPHRASE set

### ISSUE THREAD

**Issue by robkroll** [the-paperless-project/paperless#430]
Hi, if I _don't_ define a passphrase in my `docker-compose.env` file (so, not modified the file at all before the first volume is created i.e. no documents previously imported) when I run `docker-compose up -d` and `docker-compose logs` I get the following output:
```
webserver_1  |     "settings.PASSPHRASE is unset.  Input passphrase: ")
webserver_1  | EOFError: EOF when reading a line
webserver_1  | settings.PASSPHRASE is unset.  Input passphrase: Traceback (most recent call last):
webserver_1  |   File "/usr/src/paperless/src/manage.py", line 16, in <module>
webserver_1  |     "settings.PASSPHRASE is unset.  Input passphrase: ")
webserver_1  | EOFError: EOF when reading a line
webserver_1  | settings.PASSPHRASE is unset.  Input passphrase: Traceback (most recent call last):
webserver_1  |   File "/usr/src/paperless/src/manage.py", line 16, in <module>
webserver_1  |     "settings.PASSPHRASE is unset.  Input passphrase: ")
consumer_1   | settings.PASSPHRASE is unset.  Input passphrase: Traceback (most recent call last):
consumer_1   |   File "/usr/src/paperless/src/manage.py", line 16, in <module>
consumer_1   |     "settings.PASSPHRASE is unset.  Input passphrase: ")
consumer_1   | EOFError: EOF when reading a line
consumer_1   | settings.PASSPHRASE is unset.  Input passphrase: Traceback (most recent call last):
consumer_1   |   File "/usr/src/paperless/src/manage.py", line 16, in <module>
consumer_1   |     "settings.PASSPHRASE is unset.  Input passphrase: ")
consumer_1   | EOFError: EOF when reading a line
```
If I set the passphrase:
```
PAPERLESS_PASSPHRASE="secret"
```
Then it works OK. I wonder if it is somehow not setting any of the environment variables because similarly setting in `docker-compose.env` file:
```
PAPERLESS_DISABLE_LOGIN=true
PAPERLESS_INLINE_DOC=true
```
Does not have any effect -- login UI is still shown and documents are still downloaded when clicked. Any tips on how I can debug to find out if these are getting set appropriately? Many thanks.

**Comment by bmsleight** [comment]
> don't define a passphrase in my docker-compose.env

Not sure this is a bug/issue. If passphrase not set, paperless does not run. May be documentation could make this clearer, but appear to be as designed.
Propose to close in next 5 days.

**Comment by stgarf** [comment]
@robkroll Can you take a look @ #535 and see if that solves your issue?

**Comment by robkroll** [comment]
@stgarf Can confirm, #535 identified the issue. Thanks a lot!

**Comment by rukidi** [comment]
Its not final you can edit

The familly of Mr.KASOZI CHARLES and Ms NAKALANZI HARRIET with great
pleasure invites the familly of
mr/mrs.................................................. to the
INTRODUCTION CEREMONY of their daughter NALUBEGA ERINAH scheduled
27/07/2019 NAAMA  (MITYANA) starting at 10:00am
Your presence will be high recognized and appreciated
For more details
Mr. Kasozi Charles (father) 0782105360/0750991030
Ms. Nakalanzi Harriet (mother)-0704709324/0771871769
Mr.Matovu Lawrence (chairman)-0702912082/0775248339
Ms .Nampijja Ritah (Treasurer)-0708263388
 #################
Ab'enju ya Mwami KASOZI CHARLES ne Mukyala NAKALANZI HARRIET n'essanyu
lingi bayiita familly ya Mw/Mky
............................................................ ku mukolo
gw'okwanjula kwa muwala wabwe NALUBEGA ERINAH nga 27/07/2019 E  NAAMA
(MITYANA) okutandiika ssaawa 10:00am ez'okumakya
Okuberawoko kujja kuwesa nnyo omukolo ekitiibwa
Okumannya ebirala kubaira kubano
Mw .kasozi Charles (taata) 0782105360/0750991030
Mky.Nakalanzi Harriet (maama) 0771871769/0704709324
Mw .Matovu Lawrence (ssentebe)-0775248349/0702912082
Mky.Nampijja Ritah (Omuwanika)-0708263388
