### ISSUE TITLE
Retroactively enable encryption?

### ISSUE THREAD

**Issue by stgarf** [the-paperless-project/paperless#459]
Is it possible to retroactively encrypt already imported documents when enabling encryption?

If not, consider this a feature request for that. Thanks!

EDIT: Same goes for the reverse, if I disable encryption does it GPG decrypt everything and leave me all set to move on?

**Comment by danielquinn** [comment]
Have a look at `./manage.py change_storage_type --help`.  The output should give you everything you need to switch your system back & forth :-)

**Comment by stgarf** [comment]
Awesome, thanks @danielquinn I've opened #510.
