### ISSUE TITLE
Docker - Be Sure to not lose documents

### ISSUE THREAD

**Issue by Ulli2k** [the-paperless-project/paperless#505]
Hello!
I just switched to the docker world. I got paperless running with your .yml and .env file. The container image came from dockerhub. It works straight forward!!

I have a few questions:
* Is this the right way to have paperless in productive mode?
* How can I be sure that after a container image update I do not loose my documents?
   I just exported the "consumer" & "export" volumes. (does it make sense to export the sql database?)
* What is the best way to backup by documents? Is there a better way than exporting all documents with the exporter and copy it to an other location (cronjob)

Thanks a lot!

**Comment by bmsleight** [comment]
Docker - Yes
Exporter and back-up - https://paperless.readthedocs.io/en/latest/utilities.html#the-exporter

Hope this helps

**Comment by Ulli2k** [comment]
Is it useful to safe the sql database instead?

**Comment by bmsleight** [comment]
no
