### ISSUE TITLE
Fix Travis integration

### ISSUE THREAD

**Issue by danielquinn** [the-paperless-project/paperless#512]
As per @pitkley's comment in #470, the Travis integration appears to be broken since the move to an organisation.  I've approved the addition of Travis, but it doesn't appear to have had an effect.

* I created a dummy pull request (#511) and Travis didn't start
* I logged into Travis, and [triggered a manual build](https://travis-ci.org/the-paperless-project/paperless/builds/494770832), and that worked just fine.

I checked out the webhooks on this repo too:

![Screenshot of webhooks](https://user-images.githubusercontent.com/218205/52938176-e1cda480-3358-11e9-8c44-c3933cc87dc3.png)

So now I'm not sure what needs to be done.  Input is appreciated.

**Comment by stgarf** [comment]
@danielquinn For the fix take a look at #510. I opened it before the repo was converted to an Org and it got caught up in the Travis wonkiness.

The easy fix is to simply close and then re-open the PR. Two clicks, should take two seconds per PR that is in a weird state.

**Comment by pitkley** [comment]
@stgarf I can confirm that this seems to work great. I have closed and re-opened 3 or 4 PRs now, and Travis picked up the build immediately each time. Thanks for finding such an easy fix! 🎉

**Comment by danielquinn** [comment]
It sounds like this is fixed, so I'm going to close this now.
