### ISSUE TITLE
Use Dockerhub to build Docker image

### ISSUE THREAD

**Issue by lbischof** [the-paperless-project/paperless#514]
Add an automated build on Dockerhub. If you want, I can help managing the Docker part of this project.

**Comment by Beverdam** [comment]
Hi,

I see that the images on dockerhub are outdated (or at least, not keeping up with the commits done here). Are automatic builds created or not?

**Comment by stgarf** [comment]
Hi @Beverdam you're hitting a combination of #470 and #532
