### ISSUE TITLE
Paperless.ReadTheDocs.io not receiving updates?

### ISSUE THREAD

**Issue by stgarf** [the-paperless-project/paperless#520]
Tagging @pitkley @ovv @jat255 @MasterofJOKers @danielquinn in case it's a quick fix. 

I have a hunch that during "The Great Paperless Organization Migration of 2019&trade;" webhooks for ReadTheDocs.io were somehow messed up. If they could be re-created and re-triggered that would be neat (I'm not too familiar with RTD.io, perhaps it's based on git tags and since 2.7.0 is the latest tagged version that's the "latest" docs we get).

Bottom of the page references an older commit:
`© Copyright 2015, Daniel Quinn Revision 7b4785bd.`

https://docs.readthedocs.io/en/stable/webhooks.html

**Comment by jat255** [comment]
Yes, if you look at the [project page](https://readthedocs.org/projects/paperless/), the last build was built about 2 months ago, which I think would match up with the 2.7.0 release. The proper setup would be to have the "stable" branch of the docs point to the latest tagged release, and the "latest" branch point to the docs that are automatically built with every commit to master. 

Based off these instructions: 
![image](https://user-images.githubusercontent.com/1278301/53703248-ab3b6380-3e07-11e9-9522-69f5951f4880.png)

It looks like the "latest" should be connected to Pushes, and the "stable" should be connected to Tag Creation. I don't have access to the projects' admin settings (I think only @danielquinn does), and that's where this needs to happen, I think.

**Comment by jat255** [comment]
I think the project repository link also needs to be updated in RTD, as it still points to danielquinn/paperless instead of the-paperless-project/paperless

**Comment by stgarf** [comment]
@danielquinn Wondering if you can possibly explore expanding RTD.io access you some of the people you've made contributors to this repo -- like jat255.

**Comment by danielquinn** [comment]
Hi guys, I had a look at the RTD config and sure enough, this was a hold-over from the Great Migration.  I've reconfigured RTD to (a) pull from the new repo URL and (b) use their webhooks system.  I manually ran a build and [everything appears to be ok](https://readthedocs.org/projects/paperless/).

Thanks for the heads-up on this.  If it fails to update during a push, just let me know and I'll poke it with a stick to make it work properly.

As for adding additional maintainers to the RTD integration, they don't seem to have a differentiation between "admin" and "maintainer", so I'm not comfortable adding anyone new as it only takes one bad actor to lock out everyone else.  This isn't a reflection on @jat255 (he seems cool to me) ;-) but as I don't know anyone personally, I'm just not comfortable with the possibility that my judgement may be wrong and that such a mistake could screw the project.

I'll close this now, as I think the issue should be solved.  If I'm wrong about that, or you think this warrants further discussion, feel free to re-open.

**Comment by jat255** [comment]
@danielquinn No offense taken... I could be a deep-state spy sent to infiltrate small to medium-scale open source projects' documentation systems :smirk: 

Glad it was an easy fix!
