### ISSUE TITLE
I added a stackshare profile for this project

### ISSUE THREAD

**Issue by danielquinn** [the-paperless-project/paperless#538]
I've been toying with [StackShare](https://stackshare.io/) for a while now [¹](https://stackshare.io/danielquinn/aletheia) [²](https://stackshare.io/danielquinn/albatross) and thought it might be fun to do [one for Paperless](https://stackshare.io/the-paperless-project/the-paperless-project).  The site allows for others to be added to the team, so anyone who wants to have rights to modify the stack (maybe I missed something?) just ask and I'll add you.  It also comes with a nifty badge:

[![StackShare](http://img.shields.io/badge/tech-stack-0690fa.svg?style=flat)](https://stackshare.io/the-paperless-project/the-paperless-project)

It's just an idea, so if others think this is dumb, feel free to say so and just close the ticket.  I won't be annoyed, and will just delete the stack.

**Comment by jat255** [comment]
:+1: visibility is always good!

**Comment by jat255** [comment]
Whoops,,,

**Comment by jdorfman** [comment]
@danielquinn this is great! If you add some stack decisions I will feature Paperless in the next (or near future) [weekly newsletter](https://stackshare.io/weekly).

@jat255 if you (or anyone) have any StackShare questions please let me know.

**Comment by danielquinn** [comment]
Hooray for publicity!  Alright I've added a bunch of explanations, and created a pull request to add the badge to the readme.

**Comment by jdorfman** [comment]
@danielquinn awesome. Out of curiosity, did you get this idea from the weekly newsletter or just found the badge?

**Comment by danielquinn** [comment]
*[Takes a minute to dig through his email searching for `badge` and `stackshare`]*.  Nope, I don't even have an email with that in it.  I must have just found the feature while poking around on the site.

**Comment by jdorfman** [comment]
Thank you for the feedback =)
