### ISSUE TITLE
Any interest in cloud-based OCR (Google Cloud, AWS, etc)?

### ISSUE THREAD

**Issue by diveflo** [the-paperless-project/paperless#560]
Hi,

I recently played around with some Google Cloud and AWS services and was very surprised about their OCR quality - especially compared to tesseract.
Additionally I saw that e.g. Google gives you 1000 pages for free each month, which would at least cover my needs more than sufficient.
Stuff like entity analysis could potentially even be used to figure out Correspondents etc.
Obviously there is a debate wrt data privacy.
Hence why I’m asking if there is even any interest in something like this for paperless? The plugin architecture should hopefully allow for a clean separation and thereby easy on/off toggling for the user.

Let me know what you think!

**Comment by danielquinn** [comment]
Personally, I'm strongly opposed to dependency on any cloud-based service for Paperless as this has always been a self-hosted project designed for curating potentially very private documents.  The idea of sending a scan of my immigration documents to Google is the reddest of red flags in my book.

If there's significant support for it, I'd be open to making it optional, but frankly, for how we use Tesseract (we only use it to compile text for searching) I think it's just fine as-is.
