### ISSUE TITLE
re.error: nothing to repeat at position 2

### ISSUE THREAD

**Issue by kj21** [the-paperless-project/paperless#568]
Great work with Paperless, It's making my paperwork less time consuming. 
Recently I have been getting a regex error while running the consumer. The process quits with the line "re.error: nothing to repeat at position 2" in the Traceback. It seems to relate to the systems Python file "sre_parse.py" and the line 651:

`raise source.error("nothing to repeat",
                                   source.tell() - here + len(this))`

It seems to interpret the "+" as a repetition symbol in the regexp. I'm wondering how to fix this, since I don't feel comfortable messing around in the systems Python files.

**Comment by kj21** [comment]
`consumer_1   | Traceback (most recent call last):
consumer_1   |   File "/usr/src/paperless/src/manage.py", line 11, in <module>
consumer_1   |     execute_from_command_line(sys.argv)
consumer_1   |   File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
consumer_1   |     utility.execute()
consumer_1   |   File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 365, in execute
consumer_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
consumer_1   |   File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
consumer_1   |     self.execute(*args, **cmd_options)
consumer_1   |   File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 335, in execute
consumer_1   |     output = self.handle(*args, **options)
consumer_1   |   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 96, in handle
consumer_1   |     self.loop_inotify(mail_delta)
consumer_1   |   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 129, in loop_inotify
consumer_1   |     self.loop_step(mail_delta)
consumer_1   |   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 121, in loop_step
consumer_1   |     self.file_consumer.consume_new_files()
consumer_1   |   File "/usr/src/paperless/src/documents/consumer.py", line 112, in consume_new_files
consumer_1   |     if not self.try_consume_file(file):
consumer_1   |   File "/usr/lib/python3.7/contextlib.py", line 74, in inner
consumer_1   |     return func(*args, **kwds)
consumer_1   |   File "/usr/src/paperless/src/documents/consumer.py", line 158, in try_consume_file
consumer_1   |     date
consumer_1   |   File "/usr/src/paperless/src/documents/consumer.py", line 228, in _store
consumer_1   |     relevant_tags = set(list(Tag.match_all(text)) + list(file_info.tags))
consumer_1   |   File "/usr/src/paperless/src/documents/models.py", line 84, in match_all
consumer_1   |     if tag.matches(text):
consumer_1   |   File "/usr/src/paperless/src/documents/models.py", line 108, in matches
consumer_1   |     if re.search(r"\b{}\b".format(word), text, **search_kwargs):
consumer_1   |   File "/usr/lib/python3.7/re.py", line 183, in search
consumer_1   |     return _compile(pattern, flags).search(string)
consumer_1   |   File "/usr/lib/python3.7/re.py", line 286, in _compile
consumer_1   |     p = sre_compile.compile(pattern, flags)
consumer_1   |   File "/usr/lib/python3.7/sre_compile.py", line 764, in compile
consumer_1   |     p = sre_parse.parse(p, flags)
consumer_1   |   File "/usr/lib/python3.7/sre_parse.py", line 930, in parse
consumer_1   |     p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
consumer_1   |   File "/usr/lib/python3.7/sre_parse.py", line 426, in _parse_sub
consumer_1   |     not nested and not items))
consumer_1   |   File "/usr/lib/python3.7/sre_parse.py", line 651, in _parse
consumer_1   |     source.tell() - here + len(this))
consumer_1   | re.error: nothing to repeat at position 2`

**Comment by kj21** [comment]
Traceback (most recent call last):
File "/usr/src/paperless/src/manage.py", line 11, in <module>
  execute_from_command_line(sys.argv)
File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
  utility.execute()
File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 365, in execute
  self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
  self.execute(*args, **cmd_options)
File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 335, in execute
  output = self.handle(*args, **options)
File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 96, in handle
  self.loop_inotify(mail_delta)
File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 129, in loop_inotify
  self.loop_step(mail_delta)
File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 121, in loop_step
  self.file_consumer.consume_new_files()
File "/usr/src/paperless/src/documents/consumer.py", line 112, in consume_new_files
  if not self.try_consume_file(file):
File "/usr/lib/python3.7/contextlib.py", line 74, in inner
  return func(*args, **kwds)
File "/usr/src/paperless/src/documents/consumer.py", line 158, in try_consume_file
  date
File "/usr/src/paperless/src/documents/consumer.py", line 228, in _store
  relevant_tags = set(list(Tag.match_all(text)) + list(file_info.tags))
File "/usr/src/paperless/src/documents/models.py", line 84, in match_all
  if tag.matches(text):
File "/usr/src/paperless/src/documents/models.py", line 108, in matches
  if re.search(r"\b{}\b".format(word), text, **search_kwargs):
File "/usr/lib/python3.7/re.py", line 183, in search
  return _compile(pattern, flags).search(string)
File "/usr/lib/python3.7/re.py", line 286, in _compile
  p = sre_compile.compile(pattern, flags)
File "/usr/lib/python3.7/sre_compile.py", line 764, in compile
  p = sre_parse.parse(p, flags)
File "/usr/lib/python3.7/sre_parse.py", line 930, in parse
  p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
File "/usr/lib/python3.7/sre_parse.py", line 426, in _parse_sub
  not nested and not items))
File "/usr/lib/python3.7/sre_parse.py", line 651, in _parse
  source.tell() - here + len(this))
re.error: nothing to repeat at position 2

**Comment by pitkley** [comment]
Thanks for reporting this @kj21. I think I found a fix and opened PR #571 for this. We'll let you know once it is fixed!

**Comment by kj21** [comment]
Beautiful! As you lined out, I replaced `r"\b{}\b".format(word), text, **search_kwargs)` in line 101 and 108 in models.py with `r"\b{}\b".format(re.escape(word)), text, **search_kwargs)` and `r"\b{}\b".format(self.match), text, **search_kwargs))` in line 114 with `r"\b{}\b".format(re.escape(self.match)), text, **search_kwargs))`. Works great. Thanks a lot!
