### ISSUE TITLE
Documentation rendering leads to wrong commands

### ISSUE THREAD

**Issue by mattelacchiato** [the-paperless-project/paperless#569]
In the documentation at readthedocs https://paperless.readthedocs.io/en/latest/setup.html#docker-method, part 4), there is a caution box. The yml line which is rendered there is completely wrong.

> command: [“document_consumer”, “–no-inotify”]

This led to the following error message:
```consumer_1   | Operations to perform:
consumer_1   |   Apply all migrations: admin, auth, contenttypes, documents, reminders, sessions
consumer_1   | Running migrations:
consumer_1   |   No migrations to apply.
consumer_1   | Unknown command: '“document_consumer”'
consumer_1   | Type 'manage.py help' for usage.
```

Solution: The quotes are not simple quotes like `"`, but `“` and `”`. Additionally, the `–` should be a `--`.

It took me several hours to figure out why my consumer doesn't start, since those characters are really hard to distinguish...

**Comment by ddddavidmartin** [comment]
Man, debugging issues like this is a nightmare! I'm glad you worked it out.

**Comment by pitkley** [comment]
@mattelacchiato thanks for fixing this. Can we close this issue?

**Comment by mattelacchiato** [comment]
Yes, thank you!
