### ISSUE TITLE
Preview to the side in edit mode

### ISSUE THREAD

**Issue by joschi36** [the-paperless-project/paperless#596]
Mostly when i want to edit the document information it would be very useful to see the pdf to the side.

![image](https://user-images.githubusercontent.com/4538306/71726720-31657380-2e38-11ea-9cd7-4b7a1862f34d.png)

Maybe it would be a good idea to embed the PDF with `<object>`.

_PS.: A rotate option would be useful too as you can see ;)_

**Comment by ddddavidmartin** [comment]
Yes please! I'd love to see this implemented. As a start I would even be happy to have a link to the document there.

**Comment by bauerj** [comment]
@joschi36 @ddddavidmartin I have implemented something like this in #597.

It would be nice if one of you could test whether this works for them.

**Comment by Nicras** [comment]
I would love to test this but I don't know how. I use docker

**Comment by bauerj** [comment]
@Nicras If you use a recent version of paperless, this should be fairly easy:

    git remote add bauerj https://github.com/bauerj/paperless
    git fetch bauerj
    git checkout pdf-preview
    docker-compose build
    docker-compose up -d

**Comment by Nicras** [comment]
I don't ;-)

I built my own docker containers without compose. But I managed to get the src folder persistent an changed the files accordingly and it works like a charm.

Makes editing documents a lot more efficient

<img width="1920" alt="2020-01-14_15-40-27" src="https://user-images.githubusercontent.com/35510003/72353599-9c3e6680-36e4-11ea-892a-ad53cdb4c5cc.png">

**Comment by bauerj** [comment]
Thanks for testing! What theme are you using there?

**Comment by Nicras** [comment]
It's just css modification to align with the style of my organizr (plex theme)
I did it by myself. I would love to share more screenshots but it's hard to grey out everything sensitive.
And I can't attach my overrides.css

Please let me know if you wanna try, I'll send it to you
