### ISSUE TITLE
No OCR in other languages?!

### ISSUE THREAD

**Issue by xsasx** [the-paperless-project/paperless#615]
Hi,

i installed my paperless under docker thats my yml:

> #paperless
>   paperless:
>     container_name: Paperless_Server  
>     image: thepaperlessproject/paperless
>     restart: always
>     volumes:
>       - ${USERDIR}/docker/paperless/data:/usr/src/paperless/data
>       - /media/external/paperless/media:/usr/src/paperless/media
>       - /media/external/paperless/consume:/consume
>     environment:
>       - PAPERLESS_OCR_LANGUAGES=deu
>       - PAPERLESS_OCR_LANGUAGE=deu
>     command: ["runserver", "XXXX:8000"]
>     networks:
>       default:
>         ipv4_address: XXXX 
> #paperless consumer		
>   consumer:
>     container_name: Paperless_Consumer  
>     image: thepaperlessproject/paperless
>     restart: always
>     depends_on:
>       - paperless
>     volumes:
>       - ${USERDIR}/docker/paperless/data:/usr/src/paperless/data
>       - /media/external/paperless/media:/usr/src/paperless/media
>       - /media/external/paperless/consume:/consume
>     command: ["document_consumer"]
> 

Tried the solution to install the OCR Language but on consumer docker it does not work - just on server  - but brings same error :

> Operations to perform:,
>   Apply all migrations: admin, auth, contenttypes, documents, reminders, sessions,
> Running migrations:,
>   No migrations to apply.,
> Starting document consumer at /consume with inotify,
> Parsers available: RasterisedDocumentParser,
> Consuming /consume/Steuer 20.02.2020.pdf,
> ** Processing: /tmp/paperless/paperless-z__d35sj/convert.png,
> 500x617 pixels, 3x16 bits/pixel, RGB,
> Input IDAT size = 334867 bytes,
> Input file size = 335044 bytes,
> ,
> Trying:,
>   zc = 9  zm = 9  zs = 0  f = 0		IDAT size = 168765,
>   zc = 9  zm = 8  zs = 0  f = 0
>   zc = 9  zm = 9  zs = 1  f = 0
>   zc = 9  zm = 8  zs = 1  f = 0
>   zc = 1  zm = 9  zs = 2  f = 0
>   zc = 1  zm = 8  zs = 2  f = 0
>   zc = 9  zm = 9  zs = 3  f = 0
>   zc = 9  zm = 8  zs = 3  f = 0
>   zc = 9  zm = 9  zs = 0  f = 1
>   zc = 9  zm = 8  zs = 0  f = 1
>   zc = 9  zm = 9  zs = 1  f = 1
>   zc = 9  zm = 8  zs = 1  f = 1
>   zc = 1  zm = 9  zs = 2  f = 1
>   zc = 1  zm = 8  zs = 2  f = 1
>   zc = 9  zm = 9  zs = 3  f = 1
>   zc = 9  zm = 8  zs = 3  f = 1
>   zc = 9  zm = 9  zs = 0  f = 2
>   zc = 9  zm = 8  zs = 0  f = 2
>   zc = 9  zm = 9  zs = 1  f = 2
>   zc = 9  zm = 8  zs = 1  f = 2
>   zc = 1  zm = 9  zs = 2  f = 2
>   zc = 1  zm = 8  zs = 2  f = 2
>   zc = 9  zm = 9  zs = 3  f = 2
>   zc = 9  zm = 8  zs = 3  f = 2
>   zc = 9  zm = 9  zs = 0  f = 3
>   zc = 9  zm = 8  zs = 0  f = 3
>   zc = 9  zm = 9  zs = 1  f = 3
>   zc = 9  zm = 8  zs = 1  f = 3
>   zc = 1  zm = 9  zs = 2  f = 3
>   zc = 1  zm = 8  zs = 2  f = 3
>   zc = 9  zm = 9  zs = 3  f = 3
>   zc = 9  zm = 8  zs = 3  f = 3
>   zc = 9  zm = 9  zs = 0  f = 4
>   zc = 9  zm = 8  zs = 0  f = 4
>   zc = 9  zm = 9  zs = 1  f = 4
>   zc = 9  zm = 8  zs = 1  f = 4
>   zc = 1  zm = 9  zs = 2  f = 4
>   zc = 1  zm = 8  zs = 2  f = 4
>   zc = 9  zm = 9  zs = 3  f = 4
>   zc = 9  zm = 8  zs = 3  f = 4
>   zc = 9  zm = 9  zs = 0  f = 5
>   zc = 9  zm = 8  zs = 0  f = 5
>   zc = 9  zm = 9  zs = 1  f = 5
>   zc = 9  zm = 8  zs = 1  f = 5
>   zc = 1  zm = 9  zs = 2  f = 5
>   zc = 1  zm = 8  zs = 2  f = 5
>   zc = 9  zm = 9  zs = 3  f = 5
>   zc = 9  zm = 8  zs = 3  f = 5
>                                
> ,
> Selecting parameters:,
>   zc = 9  zm = 9  zs = 0  f = 0		IDAT size = 168765,
> ,
> Output file: /tmp/paperless/paperless-z__d35sj/optipng.png,
> ,
> Output IDAT size = 168765 bytes (166102 bytes decrease),
> Output file size = 168822 bytes (166222 bytes = 49.61% decrease),
> ,
> Processing sheet #1: /tmp/paperless/paperless-z__d35sj/convert-0000.pnm -> /tmp/paperless/paperless-z__d35sj/convert-0000.unpaper.pnm,
> [pgm_pipe @ 0x556f1100cf80] Stream #0: not enough frames to estimate rate; consider increasing probesize,
> [image2 @ 0x556f1100e600] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.,
> [image2 @ 0x556f1100e600] Encoder did not produce proper pts, making some up.,
> OCRing the document,
> Parsing for eng,
> Parsing for deu,
> Processing sheet #1: /tmp/paperless/paperless-z__d35sj/convert-0000.pnm -> /tmp/paperless/paperless-z__d35sj/convert-0000.unpaper.pnm,
> Processing sheet #1: /tmp/paperless/paperless-z__d35sj/convert-0000.unpaper.pnm -> /tmp/paperless/paperless-z__d35sj/convert-0000.unpaper.unpaper.pnm,
> [pgm_pipe @ 0x55864e048f80] Stream #0: not enough frames to estimate rate; consider increasing probesize,
> [pgm_pipe @ 0x55a2d26a7f80] Stream #0: not enough frames to estimate rate; consider increasing probesize,
> [image2 @ 0x55864e04a600] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.,
> [image2 @ 0x55864e04a600] Encoder did not produce proper pts, making some up.,
> [image2 @ 0x55a2d26a9600] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.,
> [image2 @ 0x55a2d26a9600] Encoder did not produce proper pts, making some up.,
> OCRing the document,
> Parsing for eng,
> Parsing for deu,
> **PARSE FAILURE for /consume/Steuer  20.02.2020.pdf: The guessed language (de) is not available in this instance of Tesseract**

**Comment by Tooa** [comment]
From your log

```bash
OCRing the document,
Parsing for eng,
Parsing for deu,
PARSE FAILURE for /consume/Steuer 20.02.2020.pdf: The guessed language (de) is not available in this instance of Tesseract
```

... it seems like `paperless` ignores your language settings i.e. `PAPERLESS_OCR_LANGUAGES=deu`. Probably because the consumer is not aware of these env vars. Can you add both variables as environment of the consumer too?

```bash
environment:
    - PAPERLESS_OCR_LANGUAGES=deu
    - PAPERLESS_OCR_LANGUAGE=deu
```

**Comment by xsasx** [comment]
Hey Uli!

Looking better ! 

>   File "/usr/src/paperless/src/documents/consumer.py", line 158, in try_consume_file,
    date = parsed_document.get_date(),
  File "/usr/src/paperless/src/documents/parsers.py", line 127, in get_date,
    text = self.get_text(),
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 110, in get_text,
    self._text = self._get_ocr(images),
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 170, in _get_ocr,
    raw_text = self._ocr([imgs[middle]], self.DEFAULT_OCR_LANGUAGE),
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 222, in _ocr,
    r = pool.map(image_to_string, itertools.product(imgs, [lang])),
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 268, in map,
    return self._map_async(func, iterable, mapstar, chunksize).get(),
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get,
    raise self._value,
pyocr.error.TesseractError: (1, b'Error opening data file /usr/share/tessdata/deu.traineddata\nPlease make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.\nFailed loading language \'deu\'\nTesseract couldn\'t load any languages!\nCould not initialize tesseract.\n'),
Operations to perform:,
  Apply all migrations: admin, auth, contenttypes, documents, reminders, sessions,
Running migrations:,
  No migrations to apply.,
Starting document consumer at /consume with inotify,
Parsers available: RasterisedDocumentParser,
Consuming /consume/Steuer AOK 20.02.2020.pdf,
** Processing: /tmp/paperless/paperless-wy3pc67i/convert.png,
500x617 pixels, 3x16 bits/pixel, RGB,
Input IDAT size = 334867 bytes,
Input file size = 335044 bytes,
,
Trying:,
  zc = 9  zm = 9  zs = 0  f = 0		IDAT size = 168765,
  zc = 9  zm = 8  zs = 0  f = 0
  zc = 9  zm = 9  zs = 1  f = 0
  zc = 9  zm = 8  zs = 1  f = 0
  zc = 1  zm = 9  zs = 2  f = 0
  zc = 1  zm = 8  zs = 2  f = 0
  zc = 9  zm = 9  zs = 3  f = 0
  zc = 9  zm = 8  zs = 3  f = 0
  zc = 9  zm = 9  zs = 0  f = 1
  zc = 9  zm = 8  zs = 0  f = 1
  zc = 9  zm = 9  zs = 1  f = 1
  zc = 9  zm = 8  zs = 1  f = 1
  zc = 1  zm = 9  zs = 2  f = 1
  zc = 1  zm = 8  zs = 2  f = 1
  zc = 9  zm = 9  zs = 3  f = 1
  zc = 9  zm = 8  zs = 3  f = 1
  zc = 9  zm = 9  zs = 0  f = 2
  zc = 9  zm = 8  zs = 0  f = 2
  zc = 9  zm = 9  zs = 1  f = 2
  zc = 9  zm = 8  zs = 1  f = 2
  zc = 1  zm = 9  zs = 2  f = 2
  zc = 1  zm = 8  zs = 2  f = 2
  zc = 9  zm = 9  zs = 3  f = 2
  zc = 9  zm = 8  zs = 3  f = 2
  zc = 9  zm = 9  zs = 0  f = 3
  zc = 9  zm = 8  zs = 0  f = 3
  zc = 9  zm = 9  zs = 1  f = 3
  zc = 9  zm = 8  zs = 1  f = 3
  zc = 1  zm = 9  zs = 2  f = 3
  zc = 1  zm = 8  zs = 2  f = 3
  zc = 9  zm = 9  zs = 3  f = 3
  zc = 9  zm = 8  zs = 3  f = 3
  zc = 9  zm = 9  zs = 0  f = 4
  zc = 9  zm = 8  zs = 0  f = 4
  zc = 9  zm = 9  zs = 1  f = 4
  zc = 9  zm = 8  zs = 1  f = 4
  zc = 1  zm = 9  zs = 2  f = 4
  zc = 1  zm = 8  zs = 2  f = 4
  zc = 9  zm = 9  zs = 3  f = 4
  zc = 9  zm = 8  zs = 3  f = 4
  zc = 9  zm = 9  zs = 0  f = 5
  zc = 9  zm = 8  zs = 0  f = 5
  zc = 9  zm = 9  zs = 1  f = 5
  zc = 9  zm = 8  zs = 1  f = 5
  zc = 1  zm = 9  zs = 2  f = 5
  zc = 1  zm = 8  zs = 2  f = 5
  zc = 9  zm = 9  zs = 3  f = 5
  zc = 9  zm = 8  zs = 3  f = 5
                               
,
Selecting parameters:,
  zc = 9  zm = 9  zs = 0  f = 0		IDAT size = 168765,
,
Output file: /tmp/paperless/paperless-wy3pc67i/optipng.png,
,
Output IDAT size = 168765 bytes (166102 bytes decrease),
Output file size = 168822 bytes (166222 bytes = 49.61% decrease),
,
Processing sheet #1: /tmp/paperless/paperless-wy3pc67i/convert-0000.pnm -> /tmp/paperless/paperless-wy3pc67i/convert-0000.unpaper.pnm,
[pgm_pipe @ 0x5637b166ef80] Stream #0: not enough frames to estimate rate; consider increasing probesize,
[image2 @ 0x5637b1670600] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.,
[image2 @ 0x5637b1670600] Encoder did not produce proper pts, making some up.,
OCRing the document,
Parsing for deu,
multiprocessing.pool.RemoteTraceback: ,
""",
Traceback (most recent call last):,
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker,
    result = (True, func(*args, **kwds)),
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar,
    return list(map(*args)),
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 277, in image_to_string,
    return ocr.image_to_string(f, lang=lang),
  File "/usr/lib/python3.7/site-packages/pyocr/tesseract.py", line 373, in image_to_string,
    raise TesseractError(status, errors),
pyocr.error.TesseractError: (1, b'Error opening data file /usr/share/tessdata/deu.traineddata\nPlease make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.\nFailed loading language \'deu\'\nTesseract couldn\'t load any languages!\nCould not initialize tesseract.\n'),
""",
,
The above exception was the direct cause of the following exception:,
,
Traceback (most recent call last):,
  File "/usr/src/paperless/src/manage.py", line 11, in <module>,
    execute_from_command_line(sys.argv),
  File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line,
    utility.execute(),
  File "/usr/lib/python3.7/site-packages/django/core/management/__init__.py", line 365, in execute,
    self.fetch_command(subcommand).run_from_argv(self.argv),
  File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 288, in run_from_argv,
    self.execute(*args, **cmd_options),
  File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 335, in execute,
    output = self.handle(*args, **options),
  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 97, in handle,
    self.loop_inotify(mail_delta),
  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 130, in loop_inotify,
    self.loop_step(mail_delta),
  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 122, in loop_step,
    self.file_consumer.consume_new_files(),
  File "/usr/src/paperless/src/documents/consumer.py", line 117, in consume_new_files,
    if not self.try_consume_file(file):,
  File "/usr/lib/python3.7/contextlib.py", line 74, in inner,
    return func(*args, **kwds),
  File "/usr/src/paperless/src/documents/consumer.py", line 158, in try_consume_file,
    date = parsed_document.get_date(),
  File "/usr/src/paperless/src/documents/parsers.py", line 127, in get_date,
    text = self.get_text(),
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 110, in get_text,
    self._text = self._get_ocr(images),
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 170, in _get_ocr,
    raw_text = self._ocr([imgs[middle]], self.DEFAULT_OCR_LANGUAGE),
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 222, in _ocr,
    r = pool.map(image_to_string, itertools.product(imgs, [lang])),
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 268, in map,
    return self._map_async(func, iterable, mapstar, chunksize).get(),
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get,
    raise self._value,
pyocr.error.TesseractError: (1, b'Error opening data file /usr/share/tessdata/deu.traineddata\nPlease make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.\nFailed loading language \'deu\'\nTesseract couldn\'t load any languages!\nCould not initialize tesseract.\n'),
Operations to perform:,
  Apply all migrations: admin, auth, contenttypes, documents, reminders, sessions,
Running migrations:,
  No migrations to 

 apply.,

**Comment by xsasx** [comment]
I think that’s the problem:

> pyocr.error.TesseractError: (1, b'Error opening data file /usr/share/tessdata/deu.traineddata\nPlease make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.\nFailed loading language \'deu\'\nTesseract couldn\'t load any languages!\nCould not initialize tesseract.\n')
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, documents, reminders, sessions
Running migrations:
  No migrations to apply.

**Comment by xsasx** [comment]
Work now - problem was that not just the Server need the OCR-deu files and the settings. Also the consumer need it.

So you need to manual install the OCR for deu on consumer and server (in docker my consumer had no internet connection so must setup also the network for it)


than on cli :

> 
apk --no-cache --update add tesseract-ocr-data-deu
