### ISSUE TITLE
Consumer Share recursive scann ?

### ISSUE THREAD

**Issue by xsasx** [the-paperless-project/paperless#617]
Hi, 

I have setup all within 2 Docker containers. All is working now without a problem.

During my workflow I have noticed something. I want to have the scanned data (physically the files) also sorted. So I dont wanna just have the "MS Sharepoint" point of view - like it dont cares who the data is and just sort in PaperlessGUI.

So I wanna have a it like "Consumer Folder" could be scanned by paperless rekursive. Than I can have also a data folder structure like

Consumer Folder/Bank/2019
Consumer Folder/Invoice/2019
Consumer Folder/Health/2019 and so on 

I sort it directly after a Scan and Paperless will also import the files i have saved in subdirs under the main Consumer Share.

Is that possible ?? !

**Comment by xsasx** [comment]
How paperless work ? If above not possible - does paperless have an own copy of the file after consument it ? So that after its imported in paperless i can sort the scanned files like i want ?

**Comment by erikarvstedt** [comment]
Paperless ignores all folders in the consume directory. See [here](https://github.com/the-paperless-project/paperless/pull/539) for the technical reasons.

**Comment by xsasx** [comment]
I see - could you please answere this than I know maybe how I can handle/or work with my workflow:

> How paperless work ? If above not possible - does paperless have an own copy of the file after consument it ? So that after its imported in paperless i can sort the scanned files like i want ?

**Comment by erikarvstedt** [comment]
After consumption Paperless moves the file from the consumption dir to its internal storage.
You can then sort the documents in the webinterface by these properties: title, created date, added date, correspondent.

**Comment by xsasx** [comment]
ok thanks
