### ISSUE TITLE
500 Server Error when trying to add tag to multiple checked documents (non-docker)

### ISSUE THREAD

**Issue by stueja** [the-paperless-project/paperless#648]
When I went to Documents and selected a correspondent, so that only documents of this correspondent were shown.
I ticked the box on some of them and selected "Add tag to selected documents". After I hit the "Go" button, I received a "500 Server Error" from nginx.

Since nginx is "only" the proxy to paperless's webserver (django?) I can't really get much information out of nginx's logfiles. 

I'd be glad if someone pointed me into a direction which allows me to debug, or fix.

**Comment by totti4ever** [comment]
I think I know this the most, when the consumer consumes files and writes to the database at the same time as my request through UI

**Comment by MasterofJOKers** [comment]
Could you elaborate a little more on your setup? How do you start paperless?

**Comment by stueja** [comment]
@MasterofJOKers , paperless is being started by two systemd service files:
```
[Unit]
Description=Paperless consumer

[Service]
User=http
Group=http
ExecStart=/usr/bin/python /usr/share/webapps/paperless/src/manage.py document_consumer

[Install]
WantedBy=multi-user.target
```

```
[Unit]
Description=Paperless webserver

[Service]
User=http
Group=http
ExecStart=/usr/bin/python /usr/share/webapps/paperless/src/manage.py runserver 127.0.0.1:8000

[Install]
WantedBy=multi-user.target
```

nginx forwards the incoming connection to django:
```
server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_name paperless;

    index index.html index.htm index.php;
    access_log /var/log/nginx/paperless_access.log;
    error_log /var/log/nginx/paperless_error.log;

    location /static {

        autoindex on;
        alias /usr/share/webapps/paperless/static;

    }

    location / {

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
		proxy_hide_header X-Frame-Options;

        proxy_pass http://127.0.0.1:8000;
    }
}

```

I use Firefox to call up the paperless web page. Everything is happening in my local network.

**Comment by stueja** [comment]
Migrated my installation to docker. Closing.
