### ISSUE TITLE
Error "Message subject is unsafe"

### ISSUE THREAD

**Issue by stilltldr** [the-paperless-project/paperless#659]
Hi,

it seems as if paperless has a problem with the correspondent regex check when the subject contains "FWD:" and "AW:". When removing this prefix, the emails are processed.

https://github.com/the-paperless-project/paperless/blob/8698f92ac925baa335505b839125d97e325bb576/src/documents/models.py#L158

Using paperless from Docker:
`# ./manage.py --version

2.0.10
`
Regards

**Comment by MasterofJOKers** [comment]
This should be a duplicate of #607

**Comment by stilltldr** [comment]
No, it is a duplicate, thanks for pointing out!
