### ISSUE TITLE
Performance issues (~4 hours for 14 pages)

### ISSUE THREAD

**Issue by stueja** [the-paperless-project/paperless#668]
I recently migrated from a bare-metal installation (nginx, mariadb) to a docker-based installation (with nginx as proxy and sqlite).

I am experiencing very long processing times since then. As the title says, the last 3 documents with 14 pages took like 4 hours to process.
How can I debug this or speed this up?

**Comment by frrad** [comment]
Could you be hitting https://github.com/the-paperless-project/paperless/issues/438 ? You may have been running an older version of tesseract before updating.

Following the discussion on that issue I added 
```
OMP_THREAD_LIMIT=1
```
to my `docker-compose.env` and got a very significant speedup.

**Comment by stueja** [comment]
Wow... how could I not see that thread earlier...? Thank you for pointing that out to me. I set the `OMP_THREAD_LIMIT=1` variable now and will test.

**Comment by stueja** [comment]
Significantly faster now. Significantly! Thank you very much!
