### ISSUE TITLE
Make PAPERLESS_EMAIL_SECRET case insensitive

### ISSUE THREAD

**Issue by frrad** [the-paperless-project/paperless#678]
When I send an email from my phone sometimes the keyboard tries to capitalize things. It would be nice if the `PAPERLESS_EMAIL_SECRET` were not case sensitive so I didn't have to worry about correcting it.

I'm happy to do this work, could make it opt in with another env variable. Wanted to see how people felt about it before making the change.

**Comment by kohfuchs** [comment]
I don't think that this is a good idea. Passwords should be case sensitive because of security reasons.
